### ISSUE TITLE
Mobile SSO

### ISSUE THREAD

**Issue by skumbhat** [okta/okta-oidc-ios#126]
The current version of the repo may not be using the ASWebAuthenticationSession class from apple: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession to do SSO between Native Apps (the previous version SFAuthenticationSession used to work with iOS 11).

**Comment by IldarAbdullin-okta** [comment]
@skumbhat , thanks for reporting this. In release 2.0 we reworked AppAuth UI flow to SFSafariViewController only. We will add support of ASWebAuthenticationSession for iOS12+ devices

@anastasiiaiurok-okta , could you add support of ASWebAuthenticationSession class similar to OID implementation?

**Comment by anastasiiaiurok-okta** [comment]
Hi @skumbhat !

We did remove `SFAuthenticationSession` and `ASWebAuthenticationSession` intentionally. The reason is that API do not work for Sign Out. This is the known iOS issue (described [here](https://forums.developer.apple.com/thread/91647)).
Currently we are using `SFSafariViewController` for both `Sign In` and `Sign Out` on all the versions of iOS.

Please, let us know if you are ok with closing this issue.

**Comment by skumbhat** [comment]
Okay, how are app developers going to achieve SSO then?

-Sandeep

**Comment by anastasiiaiurok-okta** [comment]
Hi @skumbhat 
We restored usage of SFAuthenticationSession. Please, check it out and let us know if there is any issue with it.

**Comment by skumbhat** [comment]
Thank you! Just to make sure is it SFAuthenticationSession (iOS 11) or ASWebAuthentication (iOS 12+) or both?

-Sandeep

**Comment by anastasiiaiurok-okta** [comment]
@skumbhat Both of them, depending on the version of iOS.

**Comment by nbarbettini** [comment]
@skumbhat Did the latest version work for you?

**Comment by IldarAbdullin-okta** [comment]
Closing for now. Please reopen if the issue persists
