### ISSUE TITLE
Json Serialization error on MFA verify

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [okta/okta-oidc-ios#162]
Running example code snippet, can get to the point where I provide sms otp code, but each time I call verify I get: responseSerializationError(Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "factorResult", intValue: nil)], debugDescription: "Cannot initialize FactorResult from invalid String value CHALLENGE", underlyingError: nil)), 1157 bytes)

any ideas on the issue?

**Comment by IldarAbdullin-okta** [comment]
Hi @andrewvanbeek-okta ,

Please submit issues that are related to oka-auth-swift SDK into it's repo: https://github.com/okta/okta-auth-swift

Regarding the issue: What version of the SDK you use? This issue is fixed in latest SDK: [1.3.0](https://github.com/okta/okta-auth-swift/releases/tag/1.3.0)
Please also track issue in our internal ticket: OKTA-224371-AuthN iOS SDK: Adding of new 'factorResult' value on server side breaks json parsing on SDK side

Ildar
