### ISSUE TITLE
Codebase is old Swift version (4.2; current is 5.1)

### ISSUE THREAD

**Issue by adamlatitude** [okta/okta-oidc-ios#186]
Hi - in the sample apps I submitted the same issue and got a very quick response. Any chance to update this code to Swift 5.1 also?

**Comment by IldarAbdullin-okta** [comment]
Hi @adamlatitude ,

Could you tell me more about the issue? I'm pretty sure that Okta's SDK should be compatible with Swift 5

Ildar

**Comment by gloryluu** [comment]
@IldarAbdullin-okta I think he's mentioning about the compile warning ?

**Comment by adamlatitude** [comment]
Hi, was looking at all the code samples in this repo. While I can convert them like anyone else it would be great to have an official Swift 5 version.

**Comment by bdpdx** [comment]
Is this framework an official Okta product?  It seems ridiculous that a vendor would allow their product to go months and months without such a simple update.  When your product is included in an app with Xcode 11 it generates a warning that says "Conversion to Swift 5 is available."  We are diligent about removing both errors and warnings in our codebase but this one we can't get rid of because we don't want to modify the official OktaOidc release.

Would you please open your framework in Xcode 11.5, make the necessary changes to update to Swift 5 and ship a fix?

**Comment by IldarAbdullin-okta** [comment]
Hi @bdpdx ,

There are certain versions requirements for the library - what minimal Swift version to support, what minimal deployment targets to support and etc. We can't immediately update Swift code base to latest as we want to give some time to developers to update their environment and code bases
In next release we will update Swift version requirement in podspec file to 5.0

Ildar

**Comment by IldarAbdullin-okta** [comment]
Swift version has been updated to 5.0 in 3.8.0 release
