### ISSUE TITLE
AppAuth-iOS dependency

### ISSUE THREAD

**Issue by kirillyakimovich** [okta/okta-oidc-ios#215]
Could you please explain why AppAuth-iOS is just copied and not added as a dependency?
Is it worth to create a PR changing this?

**Comment by IldarAbdullin-okta** [comment]
Hi @kirillyakimovich ,

Okta added custom modifications into AppAuth-iOS code, so it can't be used as a pod dependency.
Also this helps us to keep library Carthage compatible

Does that answer your question?

Ildar

**Comment by kirillyakimovich** [comment]
Hi @IldarAbdullin-okta ,
Thank you for the response, actually now I have more questions:
What are these changes?
Why are they needed?
And (lent skip Carthage support for now)
Why not contributed to upstream?
Why not a fork?

**Comment by IldarAbdullin-okta** [comment]
- There are some Okta specific changes/fixes that doesn't make sense to contribute to OIDC Core
- Also we don't want to depend on AppAuth-iOS release process especially for urgent issues and new iOS releases
- AppAuth-iOS not forked because of Carthage and SPM(future)

Do you have any issues with the current library structure?
