### ISSUE TITLE
No option to signOut without a UIViewController

### ISSUE THREAD

**Issue by vijkum261** [okta/okta-oidc-ios#216]
Hello Team,
Similar to authenticate method of OktaOidc why there is nothing for signOut without a `UIViewController`? 
This allows to call okta apis without a UI dependency and helps to put custom sign-in and sign-out implementation.
Plus UIViewController has been replaced with View protocol in SwiftUI and current okta-oidc doesn't support Views.

**Comment by IldarAbdullin-okta** [comment]
Hi @vijkum261 ,

Propagation of UIViewController is the requirement of underlying `AppAuth-iOS` SDK. We can't get rid of it. If you are interested in custom UI implementation and you use Okta endpoints for authentication then you can take a look at our AuthN SDK: https://github.com/okta/okta-auth-swift

Ildar

**Comment by vijkum261** [comment]
Why is it only needed for signOut? authenticate, resetPassword etc doesn't need it.
And, the customUI implementation doesn't have anything for signOut.

Also, is there any released planned for SwiftUI flavor too considering its going to take over UIKit.

**Comment by IldarAbdullin-okta** [comment]
It is valid concern, however OIDC core uses `ASWebAuthenticationSession` class for browser based oidc flows. Sign-out uses `ASWebAuthenticationSession` as well, and `ASWebAuthenticationSession` requires presentation context.

Regarding SwiftUI, currently there are no plans to support SwiftUI for OIDC SDK

**Comment by vijkum261** [comment]
If okta is able to signIn without a presentation context, I would assume signOut can also happen the same way. Correct me if am wrong?
Maybe something for enhancement.

**Comment by IldarAbdullin-okta** [comment]
I see what you are saying. Probably we can keep track on type of sign-in(regular oidc sign-in vs okta's oidc extension) and clean cookies based on that. We can take this as an enhancement and investigate further. Thanks!

**Comment by oleggnidets-okta** [comment]
Hey @vijkum261,
Sorry for late response but better late than never :) 

Sign out from Okta works similar to sign in, because it opens `ASWebAuthenticationSession` screen. In that screen, iOS ends a session and signs out the user from Okta, clears cookies. There's no way to clear the sessions/cookies outside of `ASWebAuthenticationSession`. That's the reason why the parameter `presenter` is required. 

If you want to implement custom logout I suggest you `OktaOidcStateManager` to revoke tokens (ID, Access, Refresh). You may use implementation from `OktaOidcSignOutHandler`. Note, this won't clear cookies of `ASWebAuthenticationSession` (the reason above). 
I am not aware about your case but you may benefit from the flag [`noSSO`](https://github.com/okta/okta-oidc-ios#disable-single-sign-on-for-the-authentication-session).
