### ISSUE TITLE
iOS OKTA browser-sign-in login page is not getting localised.

### ISSUE THREAD

**Issue by khan-rehan** [okta/okta-oidc-ios#338]
### Describe the bug?

Hi Okta team,
OKTA browser-sign-in page doesn't get localized with the default locale of the device.
What needs to be added to localize OKTA browser-sign-in page.

Please refer the below trail for reference:
https://github.com/okta/okta-oidc-ios/issues/312

Video Link:
https://user-images.githubusercontent.com/42263217/156175729-f39335fe-2f46-4536-90a5-0f22d179c4e0.mp4

### What is expected to happen?

Browser Login page should be localized  according to the device locale.

### What is the actual behavior?

Everything appears to be in english

### Reproduction Steps?

Set the device language to German
Go on the application and click on the country and when okta browsing page appears all the text appears to be in english.

### SDK Version(s)

SDK Versions:  3.10.4

**Comment by mikenachbaur-okta** [comment]
This is interesting, since the Okta Sign-in Widget should automatically support localization in many different languages, including German.  Looking at the linked ticket, and that the problem wasn't reproducible by @oleggnidets-okta, this might be a configuration issue within your application. Is there a possibility that the app itself isn't localized in the desired language, which might be preventing that setting from being passed down to ASWebAuthenticationSession?

**Comment by khan-rehan** [comment]
This issue is resolved.
