### ISSUE TITLE
KeyChain App Group Not Supported

### ISSUE THREAD

**Issue by rohit3d2003** [okta/okta-oidc-ios#343]
### Describe the bug?

We have multiple iOS applications that share the authentication response (access token, ID token etc.) but it seems the current implementation of OktaOidcKeyChain does support use of access groups but it hasn't been levered or exposed as such in 'OktaOidcStateManager' class. Looking for suggestions on this:

**OktaOidcKeyChain.swift**
<img width="896" alt="Screen Shot 2022-05-23 at 1 26 54 PM" src="https://user-images.githubusercontent.com/16943885/169901048-5c356be9-e147-4900-aa42-ce870efcaf32.png">

**OktaOidcStateManager**
<img width="672" alt="Screen Shot 2022-05-23 at 1 25 40 PM" src="https://user-images.githubusercontent.com/16943885/169901081-ffd7fb51-25ec-4ce0-9e9e-34ff9336e8d3.png">

### What is expected to happen?

Provide an ability to pass Access Group to OktaOidcStateManager

### What is the actual behavior?

Not currently supported

### Reproduction Steps?

Same as above

### SDK Version(s)

3.11.1

**Comment by mikenachbaur-okta** [comment]
Thank you for your report @rohit3d2003. We have been developing a replacement for OktaOidc in order to address many feature requests such as this one.

Please check out https://github.com/okta/okta-mobile-swift since it represents a much improved developer experience, and supports more features of the Okta platform than OktaOidc currently does. Please check out the `Credential.Security` enum, which gives you fine-grained control over how tokens are stored in the keychain.

Additionally, the new SDK supports [Device SSO](https://developer.okta.com/docs/guides/configure-native-sso/main/#exchange-existing-tokens-from-client-1-for-new-tokens-for-client-2), which can greatly improve the development process when working across app extensions or multiple applications, without needing to share access tokens between processes.

While we don't have an official date, we're nearing our 1.0 release, and would greatly appreciate feedback.
